from transformers import pipeline
import logging

logger = logging.getLogger(__name__)

class MessageRewriter:
    def __init__(self):
        self.model_name = "Qwen/Qwen2.5-0.5B-Instruct"
        self.generator = None

    def load_model(self):
        if self.generator is None:
            logger.info(f"Loading rewriting model: {self.model_name}")
            try:
                # Conversational generation pipeline
                self.generator = pipeline("text-generation", model=self.model_name, framework="pt")
                logger.info("Rewriting model loaded successfully.")
            except Exception as e:
                logger.error(f"Error loading rewriting model: {e}")
                raise e

    def rewrite_message(self, text: str, target_emotion: str, format_tone: str = None, scenario: str = None) -> str:
        if self.generator is None:
            self.load_model()
            
        emotion_lower = target_emotion.lower() if target_emotion else "neutral"
        tone_str = format_tone.lower() if format_tone else "professional"
        
        # Determine the context string
        if scenario and scenario.strip():
            context_str = f"Scenario / Context: {scenario.strip()}\nOriginal Text (if any): '{text}'"
        else:
            context_str = f"Original Text: '{text}'"
        
        # Use Chat Templates for the conversational AI
        messages = [
            {"role": "system", "content": "You are an expert communication assistant. Your task is to rewrite user messages or expand given scenarios into well-formed, grammatically correct, cohesive sentences. Complete the exact scenario the user asks for. Ensure the output message is completely generated by you, natively written in the correct tone."},
            {"role": "user", "content": f"Please intelligently write/rewrite a message based on the given context to natively sound {emotion_lower} and in a {tone_str} format. Fix all grammar, make it sound extremely natural, and do not include any prefixes or introductory text yourself - just write the final message.\n\n{context_str}"}
        ]
        
        # Apply the pre-trained chat template natively supported by the pipeline
        prompt = self.generator.tokenizer.apply_chat_template(
            messages, 
            tokenize=False, 
            add_generation_prompt=True
        )
        
        results = self.generator(
            prompt, 
            max_new_tokens=200,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
            repetition_penalty=1.1,
            num_return_sequences=1,
            return_full_text=False # Only return the fully generated assistant message
        )
        
        rewritten_text = results[0]['generated_text'].strip()
        # strip any quotes around the generated text
        rewritten_text = rewritten_text.strip('"'""+'“”‘’')
        
        # Basic cleanup: capitalize first letter and ensure it ends with punctuation
        if rewritten_text:
            rewritten_text = rewritten_text[0].upper() + rewritten_text[1:]
            if not rewritten_text.endswith(('.', '!', '?')):
                rewritten_text += '.'
            
        return rewritten_text

message_rewriter = MessageRewriter()
